import csv
from funciones import *

print (not "")

matriz = creaMatriz("top1000.csv")
reporte(matriz)
print ()
reporteMaximo(matriz)
print ()
reporteMinimo(matriz)
print ()
reporteDesviacion(matriz)
print ()
print ("Percentil 25%")
reportePercentiles(matriz,25)
print ()
print ("Percentil 50%")
reportePercentiles(matriz,50)
print ()
print ("Percentil 75%")
reportePercentiles(matriz,75)
print ()
reporteModa(matriz)

print ()
print (damePeliculaMayorIngreso(matriz))
print ()
#print (damePeliculasRango(matriz,2000,2010))
print ()
print (tituloMasLargo(matriz))
print ()
#gananciasAnualesBar(gananciasAnuales)
#gananciasAnualesLine(gananciasAnuales)
print ("Año con mayor ingresos")
print ( añoMayorIngreso (matriz))
print ()
print ("Mayor metascore")
print (mayorMetaScore (matriz))
print ()
print ("Película con más votos")
print (peliculaMayorNumeroDeVotos (matriz))
print ()
print ("Película con menos votos")
print (peliculaMenorNumeroDeVotos (matriz))
print ()
#print ("Años únicos")
#print (añosUnicos (matriz))
#print (decadas(añosUnicos(matriz)))
print ()
print( "Ganancias por década")
print( ganaciasPorDecada(matriz) )
print ()
print( "Promedio IMB por década")
print (promedioImbPorDecada ("200",matriz))